### ISSUE TITLE
オートコンプリート の検索機能を実装しているが、うまく機能しない

### ISSUE THREAD

**Issue by fujimi-ca48** [fujimi-ca48/travel_model_course#55]
【環境】
ruby 3.2.2
rails 7
jsbunding-rails esbuild
cssbunding-rails tailwaindcss

【質問】
以下を参考にオートコンプリートの検索機能を実装しましたが、検索はできるがオートコンプリートが機能していない状態で
検索フォームの下に文字列で全てtourist_spots.nameが表示されてしまっています。
オートコンプリートが機能するようにしたいのですが原因がわからず詰まってしまっています。
https://github-com.translate.goog/afcapel/stimulus-autocomplete?_x_tr_sl=en&_x_tr_tl=ja&_x_tr_hl=ja&_x_tr_pto=wapp
https://dev.to/thomasvanholder/search-autocomplete-stimulus-560p

以下の手順で実装しました。

```
yarn add stimulus-autocomplete
```
```
application.js

import { Application } from '@hotwired/stimulus'
import { Autocomplete } from 'stimulus-autocomplete'

const application = Application.start()
application.register('autocomplete', Autocomplete)
```
```
views/tourist_spots/index.html.erb

    <%= form_tag('/tourist_spots', method: :get, id: 'search-form') do %>
      <div data-controller="autocomplete" data-autocomplete-url-value="/tourist_spots/serach" role="combobox">
        <%= text_field_tag :query, params[:query], placeholder: "検索キーワードを入力", class: "px-4 py-2 border rounded-md", data: { autocomplete_target: "input" } %>
        <ul class="list-group" data-autocomplete-target="results"></ul>
      </div>
      <%= submit_tag "検索", class: "btn btn-accent ml-2" %>
    <% end %>
  
```
```
tousits_spots_controller.rb

class TouristSpotsController < ApplicationController
  def index
    @q = params[:query]
    @tourist_spots = if @q
      TouristSpot.where('name LIKE ?', "%#{@q}%").page(params[:page]).per(12)
    else
      TouristSpot.page(params[:page]).per(12)
    end
    @total_spot_item = TotalSpotItem.new
  end
    
  def show
    @tourist_spot = TouristSpot.find(params[:id])
  end
end
```
```
custom.css

.list-group {
    border: 1px solid #ccc;
    background-color: white;
    list-style: none;
    padding: 0;
    max-height: 200px;
    overflow-y: auto;
}

.list-group-item {
    padding: 8px;
    cursor: pointer;
}

.list-group-item:hover {
    background-color: #f0f0f0;
}
```

js部分が機能していないと思いデベロッパーツールでエラーの確認を行うと以下のエラーがでていたので、解消するためにsearchアクションを作成してみました。
```
application-7553c5a68980e8d7dfb6609d54c0e0d720dba6db70bc97d45e86bf71babecfb4.js:9599     GET http://localhost:3000/tourist_spots/search?q=aaa 404 (Not Found)
doFetch @ application-7553c5a68980e8d7dfb6609d54c0e0d720dba6db70bc97d45e86bf71babecfb4.js:9599
fetchResults @ application-7553c5a68980e8d7dfb6609d54c0e0d720dba6db70bc97d45e86bf71babecfb4.js:9581
onInputChange @ application-7553c5a68980e8d7dfb6609d54c0e0d720dba6db70bc97d45e86bf71babecfb4.js:9561
setTimeout (async)
(anonymous) @ application-7553c5a68980e8d7dfb6609d54c0e0d720dba6db70bc97d45e86bf71babecfb4.js:9661
application-7553c5a68980e8d7dfb6609d54c0e0d720dba6db70bc97d45e86bf71babecfb4.js:9601 Uncaught (in promise) Error: Server responded with status 404
    at extended.doFetch (application-7553c5a68980e8d7dfb6609d54c0e0d720dba6db70bc97d45e86bf71babecfb4.js:9601:15)
    at async extended.fetchResults (application-7553c5a68980e8d7dfb6609d54c0e0d720dba6db70bc97d45e86bf71babecfb4.js:9581:22)
```

一覧画面に絞り込み結果を表示したくserachアクションだと「http://localhost:3000/tourist_spots/search?query=aaa&commit=%E6%A4%9C%E7%B4%A2」に遷移して表示されてしまうため以下の様にindexアクションも実装しました。エラーは解消されたのですが検索フォームに文字を入力しても何を入力したかに関わらずtourist_spots.nameが全件表示される＆クリックできない状態です。
エラーを解消するために以下の様にコントローラを記述しましたが、そもそも記述が間違っているのでしょうか・・・。
searchアクションを消してdata-autocomplete-url-value="/tourist_spots/serach"の部分をdata-autocomplete-url-value="/tourist_spots"とすると検索フォームに文字を入力した際に一覧画面が複製させる形で表示されてしまい、うまく動作しませんでした。
参考URLが少ないため解決できず、アドバイスいただけますと幸いです。

```
tourist_spots_controller.rb

class TouristSpotsController < ApplicationController
  def index
    if params[:query]
      @tourist_spots = TouristSpot.where('name LIKE ?', "%#{params[:query]}%").page(params[:page]).per(12)
    else
      @tourist_spots = TouristSpot.all.page(params[:page]).per(12)
    end
    @total_spot_item = TotalSpotItem.new
  end
    
  def show
    @tourist_spot = TouristSpot.find(params[:id])
  end

  def search
    query = params[:query]
    @tourist_spots = TouristSpot.where('name LIKE ?', "%#{query}%")
    render partial: 'autocomplete', locals: { tourist_spots: @tourist_spots }
  end
end
```
```
_autocomplete.html.erb

<ul class="list-group">
  <% tourist_spots.each do |tourist_spot| %>
    <li class="list-group-item"><%= tourist_spot.name %></li>
  <% end %>
</ul>
```

https://github.com/fujimi-ca48/travel_model_course/pull/54/commits

**Comment by Tsuchiya2** [comment]
共有いただいた https://dev.to/thomasvanholder/search-autocomplete-stimulus-560p を元に可能な限りの回答を試みます。（もう一方のURLは翻訳ページ？に遷移して良く分からなかったです）

まずコンソールに表示されていた以下のエラーは、views/tourist_spots/index.html.erb の data-autocomplete-url-value="/tourist_spots/serach"と照らし合わせると、どこにリクエストを飛ばしているか（どのURIパターンに、なんのHTTPメソッドでリクエストを飛ばしているか）という点から考えると、tourist_spotsコントローラーにsearchアクションが定義されていないために出ていたエラーかと思います。コントローラーにその記載はされたようですがルーティングは正しく定義できているか念のため確認しておきましょう。
```
application-7553c5a68980e8d7dfb6609d54c0e0d720dba6db70bc97d45e86bf71babecfb4.js:9599     GET http://localhost:3000/tourist_spots/search?q=aaa 404 
```

次にルーティングも正しく定義できていたら、アクション内の記載は適切か確認してみてください。愚弟的には同アクション内の`@tourist_spots`は期待している値を取れているかどうかをデバッグツールなどを使って検証してみるなどです。また、render以降の記載も合わせて確認・検証してみてください。

また、参考記事のCreate results viewと手元の記載を比較して差があれば、その辺りも確認・検証してみてください。
```
<% @search_results.each do |result| %>
  <li role="option"><%= result %></li>
<% end %>
```

あとは公式GitHub https://github.com/afcapel/stimulus-autocomplete を参考にして取り組んでみてください。

**Comment by fujimi-ca48** [comment]
ルーティングを確認し昨日から色々いじってしまったため見本のようにHTML部分も再度、修正しました。
候補が全件表示されており、その中から選ぶことはできますが文字列を元に候補のメニューを表示して入力を補完してくれる機能の部分ができていない状態です。

```
 resources :tourist_spots, only: %i[index show] do
    collection do
      get :search
    end
  end
```
```
_autocomlete.heml.erb

<% @search_results.each do |result| %>
    <li role="option"><%= result %></li>
<% end %>
```
```
total_spot_items_controller.rb

 def search
      @search_results = TouristSpot.pluck(:name)
      render partial: 'autocomplete'
    end
```
添付いただいたhttps://github.com/afcapel/stimulus-autocompleteを元に昨日も実装しており、以下を書くことで文字を打つと候補のメニューが絞り込まれるイメージでいましたが認識間違っていますでしょうか・・・。

```
import { Application } from 'stimulus';
import { Autocomplete } from 'stimulus-autocomplete';
const application = Application.start();
application.register('autocomplete', Autocomplete);
```

**Comment by Tsuchiya2** [comment]
> 候補が全件表示されており、その中から選ぶことはできますが文字列を元に候補のメニューを表示して入力を補完してくれる機能の部分ができていない状態です。

こちらの記載からTouristSpotsテーブルにある全てのnameが表示されているのかと思いますが、いかがでしょうか？
（「TouristSpot.pluck(:name)」からTouristSpotsテーブルにある全てのnameが表示されているのかと思います）

そのためJSの記載の問題ではなく、以下の部分のせいかと思われます。

```ruby
# total_spot_items_controller.rb
def search
  @search_results = TouristSpot.pluck(:name)
  render partial: 'autocomplete'
end
```

当初のwhereを使った書き方で検証してみましょう。
もしwhereで取得したレコード(配列のような形になっているもの)をそのまま渡して上手く行かないようであれば、whereで取得したものに対して「pluck(:name)」を実行し、それを`@search_results`に代入してみてください。

**Comment by fujimi-ca48** [comment]
上記を試してみました。検索結果は一覧画面にそのまま表示したかったのでセッションを用いてsearchアクションの@search_resultsに代入してみました。
```
class TouristSpotsController < ApplicationController
    def index
      if params[:query]
        @tourist_spots = TouristSpot.where('name LIKE ?', "%#{params[:query]}%")
      elsif params[:prefecture_name]
        @tourist_spots = TouristSpot.where('address LIKE ?', "%#{params[:prefecture_name]}%")
      else
        @tourist_spots = TouristSpot.all
      end
  
      @tourist_spots = @tourist_spots.page(params[:page]).per(12)
      session[:search_results] = @tourist_spots.pluck(:name)
      @prefectures = TouristSpot.prefectures
      @total_spot_item = TotalSpotItem.new
    end
    
    def show
      @tourist_spot = TouristSpot.find(params[:id])
    end
  
    def search
      @search_results = session[:search_results] || []
      render partial: 'autocomplete'
    end
end
```
結果は絞り込む前の一覧画面で検索フォームに文字を入力するとやはり全件表示されている状態で
検索をした後は絞り込まれた結果がパラメーターに格納されているためquery=テストの部分の「テスト」の文字のみが表示されるようになりました。
文字列を入力しただけで検索前でもその文字列を元に候補のメニューを表示して入力を補完するには他にどこが悪いのかわからず・・・似た様な記事が見当たらない状況です・・・。
以下の実装だと文字を入力しただけで補完するのは難しいのでしょうか？
https://github.com/afcapel/stimulus-autocomplete

**Comment by Tsuchiya2** [comment]
> 上記を試してみました。検索結果は一覧画面にそのまま表示したかったのでセッションを用いてsearchアクションの@search_resultsに代入してみました。

すみません。こちらが予想していたことと異なったため、もう少し具体的に説明します。
（そもそもセッションはどのタイミングでクライアントとサーバーでやり取りするのか復習しておきましょう）

まず全件表示される件ですが、この全件表示はレコードにあるnameが全て表示されるという認識で合っていますでしょうか。その前提で以下記載します。

```ruby
TouristSpot.pluck(:name)
```

上記のコードではレコードにある全てのnameを取得して配列にするかと思いますがいかがでしょうか。行いたいこととしてユーザーが入力した値を「あいまい検索」にて候補のものを表示させたいかと思います。その際のコードは以下のようなもので実現できそうか確認・検証してみてください。

```ruby
target_records = TouristSpot.where('name LIKE ?', "%#{ユーザーが入力した値}%")
@search_results = target_records.pluck(:name)
```

**Comment by fujimi-ca48** [comment]
以下で全件表示されてしまうのは認識あっております。
```
TouristSpot.pluck(:name)
```
おっしゃる通りユーザーが入力した値を「あいまい検索」にて候補のものを表示させたいので以下の様にしたいです。
以下のコードでデバッグしてみるとパラメーターの値がnilとなっており@search_resultsに全件代入され全件表示となっているようでした。
```
  def search
      query = params[:query]
      @searched_tourist_spots = TouristSpot.where('name LIKE ?', "%#{query}%")
      @search_results = @searched_tourist_spots.pluck(:name)
      render partial: 'autocomplete'
    end
```
```
[18, 27] in /Users/yi/travel-model-course/app/controllers/tourist_spots_controller.rb
   18:     end
   19:   
   20:     def search
   21:       query = params[:query]
   22:       @searched_tourist_spots = TouristSpot.where('name LIKE ?', "%#{query}%")
   23:       @search_results = @searched_tourist_spots.pluck(:name)
   24:       byebug
=> 25:       render partial: 'autocomplete'
   26:     end
   27: end
(byebug) query
nil
(byebug) params[:query]
nil
```
以下のようにhtmlを設定している場合submitで検索ボタンを押すとform_tagで指定したindexにパラメーターが送られ
検索ボタンを押さずにフォームに文字を入力しただけの状態だとdata-autocomplete-url-value="/tourist_spots/search"でsearchアクションに送られて本来であればパラメーターで入力値を取得できるために
 @search_resultsに入力値が代入されてあいまい検索できる認識であっていますでしょうか。
```
    <div class="flex justify-center">
    <%= form_tag('/tourist_spots', method: :get, id: 'search-form', class: "flex items-center mr-4") do %>
      <div data-controller="autocomplete" data-autocomplete-url-value="/tourist_spots/search" role="combobox">
        <%= text_field_tag :query, params[:query], placeholder: "検索キーワードを入力", class: "px-4 py-2 border rounded-md", data: { autocomplete_target: "input" } %>
        <input type="hidden" name="selected_value" data-autocomplete-target="hidden">
        <ul class="list-group" data-autocomplete-target="results"></ul>
      </div>
      <%= submit_tag "検索", class: "btn btn-accent ml-2" %>
    <% end %>
```
またnilになる原因としてhtmlの記述に問題があるのではと思いform_tagでindexに送っているのが原因かと思い削除して試してみましたが、searchアクションのパラメーターはnilのままでした。
name 属性を確認しqueryになっているかを確認しましたが一致していました。
indexアクションではパラメーターが受け取れており絞り込み検索自体はできているのですが、オートコンプリートの絞り込みができていない状態です。

**Comment by Tsuchiya2** [comment]
https://github.com/afcapel/stimulus-autocomplete#:~:text=If%20you%20want%20a%20custom%20query%20parameter%20name%2C%20use%20the%20data%2Dautocomplete%2Dquery%2Dparam%2Dvalue%20attribute. こちらは確認しましたか？参考になりそうなのでよく読んでみましょう。

検証ツールを使っているのは良いと思います。
であれば、もう一歩踏み込んで上記の参考部分を踏まえて、どんなURLでリクエストが飛んでいて、それをどうキャッチできるか確認・検証してみましょう。
