### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [fujimi-ca48/travel_model_course#80]
@fujimi-ca48 
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
穴場スポット登録からモデルコース作成まで動いています。
これからより穴場スポットを登録してもらえるような見せ方を考えていけるといいですね。

## 静的コードチェックが入っている
gemのrubocopを導入して、静的なコードチェックを走らせておきましょう。
最低限のコードの可読性が保たれるのでrubocopを入れてチェックしてください。

## 就活において十分な技術力を示せる機能を実装しているか
ドラッグ&ドロップでの順番入れ替えやオートコンプリート機能などいい形で技術を取り込んでいますね！
下記に気になって点を挙げておくので、確認してみてください。
 
- 余計なファイルがあるので削除しておきましょう。（`rails`など）
- minitestを利用するのであればテストコードを書いておきましょう。RSpecを利用する想定であれば、Gemを追加してminitestは作成されないように設定しておきましょう。
- tourist_spotのモデルファイルで都道府県データを利用していますが、定数で定義するようにしましょう。使い回すデータであればactive_hashというgemを使ってActiveRecordのように扱えるといいですね。
- total_spot_items_controllerのcreateアクションがfat controllerに見えるので、modelに処理を切り出すか、privateメソッドで処理を切り出すようにしましょう。
- recommended_spots_controllerのcreateとupdateアクションも冗長なので処理を切り出してリファクタリングするようにしましょう。
- model_courses_controllerのcreateアクションもリファクタしておきましょう。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
下記の点が気になったので、修正しておきましょう。

- 穴場スポット登録時に登録できたかどうかがわからないので、ページ遷移などでフラッシュメッセージを出すようにしましょう。他にもmyリストに追加ボタンなども、追加できたかどうかがわからないので対応しておきましょう。
- ヘッダーメニューに関して、メニュー自体の数が多くないので、それぞれヘッダーに導線を出してあげましょう。
- ログイン時にはTOPページの下部にある新規登録ボタンは非表示にしておきましょう。
- 観光地一覧画面からの「マイリストを見る」「穴場スポットから選ぶ」のボタンの位置や、My穴場スポット一覧画面からの「Myリストをみる」「観光地一覧から選ぶ」「My穴場スポットを作成」ボタンの位置は整理しておきましょう。例えば、そのページの情報を新規作成するものと、他の一覧ページを参考にするものなど、分けて表示するとユーザーにとってわかりやすくなります。
- ヘッダーとフッターのボタンが背景色とかぶってちょっと文字が見えにくい感じですね、世界観を壊さずに、文字が見えやすい色を採用してみてください。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by fujimi-ca48** [comment]
レビューありがとうございます！

以下、確認点をまとめました。

1.穴場スポット登録時に登録できたかどうかがわからないので、ページ遷移などでフラッシュメッセージを出すようにしましょう。他にもmyリストに追加ボタンなども、追加できたかどうかがわからないので対応しておきましょう。

→現状、観光地一覧とMy穴場スポット一覧に設置してある「Myリストに追加」ボタンを押すと「Myリストを見る」ボタンの右上にネットショッピングの買い物かごのように赤丸で１、２などMyリストの中のスポットの合計がでカウントされるように実装しております。フラッシュメッセージではなくこちらで対応したいと考えていたのですが、body内にボタンを配置しているのでスクロールが下の方にあるとボタンが見えなくなってしまい確かにMyリストに入っているのがわからないですね・・・。ヘッターについてアドバイス頂いていたのでヘッターを整理しつつ固定してスクロール時も見える様にしヘッター上に「Myリスト」ボタンを配置してカウントでリスト追加したことがわかる様にするのはどうでしょうか？
ためにしにやってみたのですが以下の様な感じです。

<img width="1222" alt="image" src="https://github.com/fujimi-ca48/travel_model_course/assets/119108375/ceb02608-39b7-4d98-ab99-e637e1be9816">


2.ヘッダーメニューに関して、メニュー自体の数が多くないので、それぞれヘッダーに導線を出してあげましょう。

→ ここも上記の様に対応してみたのですが・・・。

3.minitestを利用するのであればテストコードを書いておきましょう。RSpecを利用する想定であれば、Gemを追加してminitestは作成されないように設定しておきましょう。
→ありがとございます！テストコードを書くのであればRSpec想定でおりましたのでminitestは作成されないように設定します！テストコードの記述は今回のアプリ作成で想定していなかったのですが本リリースまでにテストコードの記述は必須でしょうか？

**Comment by kerochelo** [comment]
@fujimi-ca48 
1,2に関して、メニューについてはよさそうですね！
できれば登録時にはメッセージは出してあげたほうがいいですね。
UI的にはメッセージを出してあげたほうがわかりやすく、登録後に数字が増えるをいう印象は最初は持っていないのでされないと違和感があるかもしれないです。

3については本リリース時には完璧まで書く必要はないですが、メイン機能やこだわっている部分についてはRSpecを書いておきましょう。そして少しずつテストカバレッジを増やしていきましょう！
